export enum RouteEnum {
	HOME = "/",
	CONTACT = "/#contact",
	EMAIL = "mailto:smup.yoga@gmail.com",
	INSTAGRAM = "https://www.instagram.com/smup_yoga/",
	ABOUT = "/about",
	CORTINA = "/yoga-cortina",
	BELLUNO = "/yoga-belluno",
	OUTDOOR = "/yoga-outdoor",
	PRIVATE_LESSONS = "/private-lessons",
	YIN = "/yin-yoga",
	ANUKALANA = "/anukalana-yoga",
	KID = "/kids-yoga",
	PILATES = "/pilates",
	PRIVACY = "/privacy-policy",
}
